export const ZJH_TAB_SLUGS = [
  'legal-education',
  'text-two-guang-geological-survey',
  'original-text',
  'text-a-view-of-legal-education',
  'text-committee-5th',
  'text-committee-6th',
  'text-committee-7th',
  'text-rule-of-law-administration',
];

const PERSON = (SITE_URL) => ({
  '@type': 'Person',
  '@id': `${SITE_URL}/zhujiahua#person`,
  name: '朱家驊',
  alternateName: ['朱騮先', 'Chu Chia-hua'],
});

const BOOK = (SITE_URL) => ({
  '@type': 'Book',
  '@id': `${SITE_URL}/zhujiahua#speeches`,
  name: '朱家驊先生言論集',
  author: { '@id': `${SITE_URL}/zhujiahua#person` },
  editor: [
    { '@type': 'Person', name: '王聿均' },
    { '@type': 'Person', name: '孫斌合' },
  ],
  inLanguage: 'zh-Hant',
});

const legalItems = [
  ['中國之法律教育問題', '1945-04-18', '303–308'],
  ['法律教育的一種看法', '1947-06-27', '308–312'],
  ['法律教育委員會第五次會議致詞', '1948-02-04', '312–316'],
  ['法律教育委員會第六次會議致詞', '1948-07-01', '316–319'],
  ['法律教育委員會第七次會議致詞', '1948-12-02', '319–324'],
  ['法治行政', '1950-09-12', '325–330'],
];

// 校訂全文各自一頁。每篇的 description 只寫該篇原文講過的事，不外推。
const TEXT_PAGES = [
  {
    slug: 'text-two-guang-geological-survey',
    textId: 'ZJH-001',
    headline: '設立兩廣地質調查所意見書',
    alternativeHeadline: '民國十六年五月於廣州',
    datePublished: '1927-05',
    pagination: '1',
    title: '〈設立兩廣地質調查所意見書〉全文｜朱家驊，1927',
    description: '朱家驊〈設立兩廣地質調查所意見書〉人工逐字校訂全文，全書首篇。1927 年 5 月於廣州：主張實行建國方略的根本在圖地測量與地質調查兩端，批評清末各省測繪詳略不一又視為軍用秘件，並指兩廣地質僅咸豐末年經一二德國學者粗加觀察。原書第 1 頁。',
    keywords: '設立兩廣地質調查所意見書,朱家驊 全文,地質調查,土地測量,建國方略,兩廣,廣州 1927',
    about: ['地質調查', '土地測量', '建國方略', '礦產', '公共機構'],
  },
  {
    slug: 'text-a-view-of-legal-education',
    textId: 'ZJH-LE-002',
    headline: '法律教育的一種看法',
    alternativeHeadline: '第三次法律教育會議講詞',
    datePublished: '1947-06-27',
    pagination: '308–312',
    title: '〈法律教育的一種看法〉全文｜朱家驊，1947',
    description: '朱家驊〈法律教育的一種看法〉人工逐頁校訂全文。1947 年 6 月 27 日第三次法律教育會議講詞：報告科目表改訂、四校增設法學院與師資培養，並主張法治是民主政治的基礎、道德無法單獨維持社會秩序。原書第 308–312 頁。',
    keywords: '法律教育的一種看法,朱家驊 全文,第三次法律教育會議,法治 民主,法學院 增設,師資培養,方孝孺',
    about: ['法治', '民主政治', '法學院', '師資培養', '道德與法律'],
  },
  {
    slug: 'text-committee-5th',
    textId: 'ZJH-LE-003',
    headline: '法律教育委員會第五次會議致詞',
    alternativeHeadline: '在教育部會議室講',
    datePublished: '1948-02-04',
    pagination: '312–316',
    title: '法律教育委員會第五次會議致詞全文｜朱家驊，1948',
    description: '朱家驊 1948 年 2 月 4 日在教育部法律教育委員會第五次會議的致詞全文（人工逐頁校訂）。龐德（Roscoe Pound）出席該次會議；本篇逐點回應龐德的中國法律教育報告書，並報告中等教育、社會教育與邊疆教育的法律課程措施。原書第 312–316 頁。',
    keywords: '法律教育委員會 第五次會議,朱家驊 龐德,Roscoe Pound 中國法律教育,新中華法系,國民法律手冊,邊疆法學人才',
    about: ['龐德報告', '憲政', '中華法系', '國際公法', '法律教育制度'],
  },
  {
    slug: 'text-committee-6th',
    textId: 'ZJH-LE-004',
    headline: '法律教育委員會第六次會議致詞',
    alternativeHeadline: '在教育部會議室講',
    datePublished: '1948-07-01',
    pagination: '316–319',
    title: '法律教育委員會第六次會議致詞全文｜朱家驊，1948',
    description: '朱家驊 1948 年 7 月 1 日在教育部法律教育委員會第六次會議的致詞全文（人工逐頁校訂）。提出兩個待研討問題：法律學系分組制應否繼續採行、法律與政治經濟應否分立兩個學院；並以 liberal training 與 professional training 的區分主張法學院專究法學。原書第 316–319 頁。',
    keywords: '法律教育委員會 第六次會議,分組制,法學院 政治經濟 分立,liberal training,professional training,民主即是法治',
    about: ['分組制', '法學院制度', '法治', '道德與禮', '職業訓練'],
  },
  {
    slug: 'text-committee-7th',
    textId: 'ZJH-LE-005',
    headline: '法律教育委員會第七次會議致詞',
    alternativeHeadline: '第七次法律教育委員會會議（原書未載地點）',
    datePublished: '1948-12-02',
    pagination: '319–324',
    title: '法律教育委員會第七次會議致詞全文｜朱家驊，1948',
    description: '朱家驊 1948 年 12 月 2 日在法律教育委員會第七次會議的致詞全文（人工逐頁校訂）。主張廢除法律學系分組制，並提出法制含創制與傳統兩種因素：法典已大體完成，此後法學家的工作重心應轉向解釋與適用。文中追述 1933 年戴季陶主持的行政法規整理委員會。原書第 319–324 頁。',
    keywords: '法律教育委員會 第七次會議,分組制 廢除,法典與習慣,解釋與適用,行政法規整理委員會,戴季陶,拿破崙民法典 德國民法典',
    about: ['分組制存廢', '法典與習慣', '比較法典史', '行政法規整理', '法學方法'],
  },
  {
    slug: 'text-rule-of-law-administration',
    textId: 'ZJH-LE-006',
    headline: '法治行政',
    alternativeHeadline: '在臺灣省青年服務團講',
    datePublished: '1950-09-12',
    pagination: '325–330',
    title: '〈法治行政〉全文｜朱家驊，1950 年在臺灣',
    description: '朱家驊〈法治行政〉人工逐頁校訂全文。1950 年 9 月 12 日在臺灣省青年服務團講：行政就是管理，法治行政就是以法為準繩的公共事務管理；談行政裁量的界限、行政訴訟與訴願，並引狄驥（Duguit）、管子與韓非子論法治。原書第 325–330 頁。',
    keywords: '法治行政 朱家驊,法治行政 全文,行政裁量,行政訴訟 訴願,狄驥 Duguit,管子 任法 明法,韓非子 大體,張釋之',
    about: ['法治行政', '行政裁量', '行政救濟', '法家', '守法教育'],
  },
];

export const ZJH_BASE_SEO = {
  name: '朱家驊研究室',
  title: '朱家驊研究室：言論集、法律教育與法治思想｜Phenom Canvas Lab',
  description: '整理《朱家驊先生言論集》的篇章、年代與場合，完整公開 1945 至 1950 年法律教育六篇的人工逐頁校訂全文。',
  keywords: '朱家驊,朱家驊先生言論集,朱騮先,Chu Chia-hua,法律教育,法治行政,教育史,中國近代史',
  type: 'CollectionPage',
  buildSchema: (SITE_URL) => [PERSON(SITE_URL), BOOK(SITE_URL)],
};

const textTabSeo = (page) => ({
  tab: 'text',
  textId: page.textId,
  name: `${page.headline}全文`,
  title: page.title,
  description: page.description,
  keywords: page.keywords,
  type: 'Article',
  buildSchema: (SITE_URL, url) => [
    PERSON(SITE_URL),
    BOOK(SITE_URL),
    {
      '@type': 'Article',
      '@id': `${url}#speech`,
      headline: page.headline,
      alternativeHeadline: page.alternativeHeadline,
      datePublished: page.datePublished,
      dateModified: '2026-07-27',
      inLanguage: 'zh-Hant',
      pagination: page.pagination,
      author: { '@id': `${SITE_URL}/zhujiahua#person` },
      isPartOf: { '@id': `${SITE_URL}/zhujiahua#speeches` },
      mainEntityOfPage: url,
      about: page.about.map((name) => ({ '@type': 'Thing', name })),
    },
  ],
});

export const ZJH_TABS_SEO = {
  ...Object.fromEntries(TEXT_PAGES.map((page) => [page.slug, textTabSeo(page)])),
  'legal-education': {
    tab: 'legal',
    name: '朱家驊的法律教育論',
    title: '朱家驊的法律教育論：六篇言論、年代與制度脈絡',
    description: '1945 至 1950 年六篇法律教育言論的完整索引與全文入口：篇名、日期、場合、原書頁碼，涵蓋法學人才的質量分佈、分組制存廢、法學院院系分立、龐德報告的回應，以及遷臺後的法治行政。',
    keywords: '朱家驊 法律教育,中國之法律教育問題,法律教育委員會,法治行政,法學教育史,民主法治',
    type: 'CollectionPage',
    buildSchema: (SITE_URL, url) => [
      PERSON(SITE_URL),
      BOOK(SITE_URL),
      {
        '@type': 'ItemList',
        '@id': `${url}#speeches`,
        name: '朱家驊法律教育言論六篇',
        numberOfItems: legalItems.length,
        itemListElement: legalItems.map(([name, datePublished, pagination], index) => ({
          '@type': 'ListItem',
          position: index + 1,
          item: {
            '@type': 'CreativeWork',
            name,
            datePublished,
            pagination,
            author: { '@id': `${SITE_URL}/zhujiahua#person` },
            isPartOf: { '@id': `${SITE_URL}/zhujiahua#speeches` },
          },
        })),
      },
    ],
  },
  'original-text': {
    tab: 'text',
    textId: 'ZJH-LE-001',
    name: '中國之法律教育問題全文',
    title: '〈中國之法律教育問題〉全文｜朱家驊，1945',
    description: '朱家驊〈中國之法律教育問題〉人工逐頁校訂全文。1945 年 4 月 18 日在教育部法律教育委員會致詞，原書第 303–308 頁。',
    keywords: '中國之法律教育問題 全文,朱家驊 全文,法律教育委員會,法學人才,民主政治,法治',
    type: 'Article',
    buildSchema: (SITE_URL, url) => [
      PERSON(SITE_URL),
      BOOK(SITE_URL),
      {
        '@type': 'Article',
        '@id': `${url}#speech`,
        headline: '中國之法律教育問題',
        alternativeHeadline: '在教育部法律教育委員會致詞',
        datePublished: '1945-04-18',
        dateModified: '2026-07-27',
        inLanguage: 'zh-Hant',
        pagination: '303–308',
        author: { '@id': `${SITE_URL}/zhujiahua#person` },
        isPartOf: { '@id': `${SITE_URL}/zhujiahua#speeches` },
        mainEntityOfPage: url,
        about: [
          { '@type': 'Thing', name: '法律教育' },
          { '@type': 'Thing', name: '民主政治' },
          { '@type': 'Thing', name: '法治' },
          { '@type': 'Thing', name: '法學人才' },
        ],
      },
    ],
  },
};
